// layout.tsx
import type { Metadata } from 'next';
import './globals.css';
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// html 태그에 두 CSS 변수를 모두 포함
		<html lang='en' >
			<body>{children}</body>
		</html>
	);
}
